### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Jjmace7** [npm/types#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/termux-setup-storage

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node:
- OS:
- platform:

```[tasklist]
### Tasks
- [ ] https://github.com/npm/types/pull/58
- [ ] https://github.com/npm/types/pull/34
```

**Comment by reggi** [comment]
**Closing:** Please use and fill our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
